"""Update the downvote table.

Revision ID: f386cd416e5a
Revises: 31ef95fd7bfc
Create Date: 2019-09-19 10:52:55.890833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f386cd416e5a'
down_revision = '31ef95fd7bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('downvotes', 'downvote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downvotes', sa.Column('downvote', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
